language: python
python:
  - "3.4"
  - "2.7"
  - "pypy"

install:
  - pip install -r requirements.txt

script:
    - cd tests
    - python testrunner.py
    - cd performance
    - python benchmark.py 5 20 500
